// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Laroche.FleetManager.Domain.Entities;

public partial class Deplacement
{
    public int DeplacementId { get; set; }

    public int? VehiculeId { get; set; }

    public int? ConducteurId { get; set; }

    public DateTime? DateDepart { get; set; }

    public DateTime? DateArrivee { get; set; }

    public string LieuDepart { get; set; }

    public string LieuArrivee { get; set; }

    public int? Kilometrage { get; set; }

    public virtual Conducteur Conducteur { get; set; }

    public virtual Vehicule Vehicule { get; set; }
}