// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Laroche.FleetManager.Domain.BaseObjects;
using System;
using System.Collections.Generic;

namespace Laroche.FleetManager.Domain.Entities;

public partial class Entretien : BaseEntity
{
    public int EntretienId { get; set; }

    public int? VehiculeId { get; set; }

    public DateTime? DateEntretien { get; set; }

    public string TypeEntretien { get; set; }

    public string Description { get; set; }

    public decimal? Cout { get; set; }

    public virtual Vehicule Vehicule { get; set; }
}