// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Laroche.FleetManager.Domain.Entities;

public partial class LigneDepense
{
    public int LigneDepenseId { get; set; }

    public int? VehiculeId { get; set; }

    public DateTime? DateDepense { get; set; }

    public decimal Montant { get; set; }

    public string Description { get; set; }

    public virtual Vehicule Vehicule { get; set; }
}