// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Laroche.FleetManager.Domain.Entities;

public partial class Vehicule
{
    public int VehiculeId { get; set; }

    public string Marque { get; set; }

    public string Modele { get; set; }

    public int? Annee { get; set; }

    public string NumeroVin { get; set; }

    public string Immatriculation { get; set; }

    public DateTime? DateAchat { get; set; }

    public string Couleur { get; set; }

    public string Statut { get; set; }

    public virtual ICollection<Affectation> Affectations { get; set; } = new List<Affectation>();

    public virtual ICollection<Deplacement> Deplacements { get; set; } = new List<Deplacement>();

    public virtual ICollection<Entretien> Entretiens { get; set; } = new List<Entretien>();

    public virtual ICollection<Incident> Incidents { get; set; } = new List<Incident>();

    public virtual ICollection<LigneDepense> LigneDepenses { get; set; } = new List<LigneDepense>();
}